# __NUMPY - (NUMERICAL PYTHON)__
__Library for numerical & Scientific Computing__

------------------------------------------------------------------------

In [1]:
import numpy as np

# ARRAYS 
1. Single Dimensional Array
2. Multi Dimensional Array 

1. __Single Dimensionl Array__

In [2]:
n1 = np.array([1,2,3,4,5,6])
n1

array([1, 2, 3, 4, 5, 6])

2. __Multi Dimensionl Array__

In [5]:
n2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

__Initializing Arrays with Zero__

In [7]:
n3 = np.zeros((4,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

__Initializing Arrays with Same number__

In [9]:
n4 = np.full((3,3),10)
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

__Initializing Arrays within Certain Range__

In [12]:
# Last parameter is Exclusive
n5 = np.arange(3,8)  # numbers from 3 to 7
n5

array([3, 4, 5, 6, 7])

In [14]:
n6 = np.arange(0,50,5)  # number from zero to 50 wtih difference of 5
n6

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])