# __TASK 15 - Advanced Numpy (reshape , concatenate, splitting , hsplit etc)__

In [ ]:
import numpy as np

In [3]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

__RESHAPE__

In [4]:

# Reshape into a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


__CONCATENATION__

In [6]:
arr2 =np.array([7, 8, 9])
np.concatenate((arr, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

__SPLITTAING__

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(arr, 3, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

__HORIZONATAL SPLITING__

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(arr, 3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

The __difference__ between split and hsplit in numpy lies in how they split the array and their use cases
- The __np.split function__ splits an array into multiple sub-arrays along a specified axis ( Split in form of Rows)
- The __np.hsplit function__ splits an array into multiple sub-arrays along the second axis (columns)